charts/ia-bail-case-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```

RIA-5503: Upgrade base helm charts to latest

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/NationalityFieldValue.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/AddressUK.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/IdValue.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/NationalityFieldValueTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/AddressUKTest.java

- added classes for Address and NationalityField.
- added unit tests.
```
[ ] Yes
[ ] No
```

RIA-5247: Added case fields in case api

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentWithDescription.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentWithMetadata.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/Document.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/HasDocument.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentWithDescriptionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentWithMetadataTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/DocumentTest.java

Added my caseField definitions for my screens, including classes for Document, DocumentWithDescription and the corresponding unit tests.
```
[ ] Yes
[X] No
```

Added caseField definitions, classes for Document, DocumentWithDescription and tests

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRole.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleLabel.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelper.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleLabelTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelperTest.java

- Fixed the user roles for Home Office.
```
[ ] Yes
[ ] No
```

RIA-5434: Added handler to populate field of 'Submitted by'

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmation.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmationTest.java

RIA-5453: Added confirmation body for Success Page On Submission

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRole.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleLabel.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicantFullNameFormatter.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/BailReferenceNumberHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/IsLegallyRepresentedForFlagHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelper.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleLabelTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicantFullNameFormatterTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/BailReferenceNumberHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/IsLegallyRepresentedForFlagHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelperTest.java

Bail pi25 sprint4

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/DateProvider.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailEvidenceDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DocumentReceiver.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DocumentsAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/SystemDateProvider.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentWithMetadataTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailEvidenceDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DocumentReceiverTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DocumentsAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/SystemDateProviderTest.java

https://tools.hmcts.net/jira/browse/RIA-5669
Added date uploaded to the grounds for bail evidence document
```
[ ] Yes
[x] No
```

RIA-5669: Added date uploaded to the grounds for bail evidence document

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

RIA-5610: Disable document generation temporarily

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingCentre.java
src/main/resources/application-hearingcentre-mapping.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingCentreTest.java

RIA-5584: Fix HearingCentre Names

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

Last bit from the previous sprint
```
[ ] Yes
[ x ] No
```

Ria 5345 uploaded bail summary notification email

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailDecisionRecordedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/RecordDecisionAppender.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/RecordDecisionAppenderTest.java

[RIA-5491](https://tools.hmcts.net/jira/browse/RIA-5491)
Small content fix
```
[ ] Yes
[X ] No
```

RIA-5491 Small content change

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/RecordDecisionAppender.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/RecordDecisionAppenderTest.java

[RIA-5493](https://tools.hmcts.net/jira/browse/RIA-5493)
Add constant for a prepopulated text field ('reason for refusal')
```
[ ] Yes
[X] No
```

RIA-5493 Add Secretary of State refusal reasons

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailDecisionRecordedConfirmation.java

[RIA-5519](https://tools.hmcts.net/jira/browse/RIA-5519)
Turn a line of text into a link in the success page of Record the Decision event (link leading to the next event)
```
[ ] Yes
[X] No
```

RIA-5519 Turn text into link

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/CaseNote.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserDetails.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/AddCaseNoteConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/AddCaseNoteHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/Appender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/model/idam/UserInfo.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetails.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsProvider.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/CaseNoteTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/AddCaseNoteConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/AddCaseNoteHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/CaseNoteAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsProviderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsTest.java

- Added new event.
- Modified UserInfo to hold more details like name.
- Added tests.

RIA-5538: Added handlers to append case notes

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsProvider.java

RIA-5538: Fix logged-in user's first name

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailEvidenceDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailEvidenceDocumentHandlerTest.java

-  Added bail evidence and bail submission document.

RIA-5610: Create Applicant Documents Collection

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[RIA-5561](https://tools.hmcts.net/jira/browse/RIA-5561)
Add `Upload Signed Decision Notice` to the handler for notifications.
```
[ ] Yes
[x] No
```

RIA-5561 Handle notification for Upload Signed Decision Notice

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5496
Added document handler for decision noticed unsigned event
```
[ ] Yes
[ x ] No
```

RIA-5496 added document handler for record decision event.

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/MoveApplicationToDecidedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MoveApplicationToDecidedHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/MoveApplicationToDecidedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MoveApplicationToDecidedHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5532
Adding event based validation into CurrentCaseStateUpdater
```
[ ] Yes
[x] No
```

Ria 5532 move to decided

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java

https://tools.hmcts.net/jira/browse/RIA-5496
Added document tag
```
[ ] Yes
[ x ] No
```

Added document tag

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/IntermediateState.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/EndApplicationConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/MoveApplicationToDecidedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/EndApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MoveApplicationToDecidedHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/IntermediateStateTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/EndApplicationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/MoveApplicationToDecidedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/EndApplicationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MoveApplicationToDecidedHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandlerTest.java

Merge dev changes to master
Merge dev changes to master
```
[ ] Yes
[ ] No
```

Merge dev to master

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5218
Adding changes to add new End Application document.
```
[ ] Yes
[X] No
```

RIA5218 End application document changes

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5553
Added document upload event on send notification handler.
```
[ ] Yes
[ x ] No
```

RIA-5553 Added uploadDocument event on send notification handler

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java

[RIA-5556](https://tools.hmcts.net/jira/browse/RIA-5556)
- Added error to be thrown when trying to submit a Direction that has a date of compliance not in the future.
```
[ ] Yes
[x] No
```

RIA-5556 Add error for dateOfCompliance not in the future

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5787
RIA-5787 - Bug fix - removing supplied by field from upload document event
```
[ ] Yes
[x] No
```

Ria 5787 upload document fix

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/Direction.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/SendDirectionConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadB1DocumentHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DirectionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/SendDirectionConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadB1DocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailEvidenceDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandlerTest.java

Merge ready of deployment tickets to master
Merge ready of deployment tickets to master
```
[ ] Yes
[ X] No
```

Master merge bail pi26 sprint2

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java

https://tools.hmcts.net/jira/browse/RIA-5800
State rename from decisionRecorded to unsignedDecision
```
[ ] Yes
[X] No
```

RIA-5800 intermediate state rename

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/UserDetailsHelper.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/editdocs/AuditDetails.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/editdocs/EditDocsAboutToSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/editdocs/EditDocsMidEventHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/EditDocsAuditLogService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/EditDocsAuditService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/EditDocsCaseNoteService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/controllers/PreSubmitCallbackController.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelper.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditLogServiceTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/editdocs/EditDocsAuditServiceTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/editdocs/EditDocsAboutToSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/editdocs/EditDocsMidEventHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/EditDocsCaseNoteServiceTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelperTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Merge dev changes to master
Merge dev changes to master
```
[ ] Yes
[ X] No
```

Merge to master bails

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseInferenceByBailNumberHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseInferenceByBailNumberHandlerTest.java

[RIA-5763](https://tools.hmcts.net/jira/browse/RIA-5763)
- Added midEvent handler to parse case number
- Added error when number doesn't match any valid format (**I'LL UPDATE THE TEXT OF THE ERROR WHEN CONFIRMED BY P.O.**)
```
[ ] Yes
[x] No
```

RIA-5763 Add MidEvent handler

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5601
Adding call to notification API for change direction due date event
```
[ ] Yes
[x] No
```

RIA-5601 - Adding notification call for change direction due date event

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeBailDirectionDueDateConfirmation.java

https://tools.hmcts.net/jira/browse/RIA-5599
Fixed typos
```
[ ] Yes
[ x] No
```

Fixed typo's

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java

https://tools.hmcts.net/jira/browse/RIA-5859
Added missing CCD to bail-case-api
```
[ ] Yes
[ x ] No
```

RIA-5859 Added submitNotificationStatus

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicantFullNameFormatter.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DetentionFacilityAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/IsLegallyRepresentedForFlagHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/StatelessHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicantFullNameFormatterTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DetentionFacilityAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/IsLegallyRepresentedForFlagHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/StatelessHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5577
- added event into pre-submit handlers to update values on overview/bail application tabs
- updated unit tests
```
[ ] Yes
[X] No
```

RIA-5577 Added edit application event to pre-submit handlers and tests

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

[https://tools.hmcts.net/jira/browse/RIA-5583](https://tools.hmcts.net/jira/browse/RIA-5583)
- Enable notifications for EDIT_BAIL_APPLICATION_AFTER_SUBMIT
```
[ ] Yes
[x] No
```

RIA-5583 Enable notifications for EDIT_BAIL_APPLICATION_AFTER_SUBMIT

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-5767
When upload signed decision is completed, the un-signed document should be replaced with the signed document in Documents tab
```
[ ] Yes
[ x] No
```

Remove unsigned document from list

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppender.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppenderTest.java

https://tools.hmcts.net/jira/browse/RIA-5885
Added Dispatch Priority to ApplicationSubmittedByAppender
```
[ ] Yes
[ x ] No
```

RIA-5885 added dispatch priority to ApplicationSubmittedByAppender

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmation.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmationTest.java

[RIA-5765](https://tools.hmcts.net/jira/browse/RIA-5765)
- remove confirmation body from confirmation of LRremoval
```
[ ] Yes
[x] No
```

RIA-5765 Change confirmation body

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java

This is to merge dev branch to master
This is to merge dev branch to master
```
[ ] Yes
[ X] No
```

Merge dev branch to master

---

charts/ia-bail-case-api/Chart.yaml
charts/ia-bail-case-api/values.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-5924
Adding AAC URL required to fix NoC bug in demo env
```
[ ] Yes
[x] No
```

RIA-5924 - NoC demo env bug fix

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/PreSubmitCallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/config/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/CcdEventAuthorizor.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/SpringAuthorizedRolesProvider.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamAuthoritiesConverter.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/PreSubmitCallbackDispatcherTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/CcdEventAuthorizorTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/SpringAuthorizedRolesProviderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamAuthoritiesConverterTest.java

https://tools.hmcts.net/jira/browse/RIA-6019
Added spring web security configuration (content path and authorised roles for events)
```
[ ] Yes
[ x ] No
```

Ria 6019 bails address api security

---

charts/ia-bail-case-api/Chart.yaml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmation.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-6040
Fixed LR StartApplication event confirmation bug
```
[ ] Yes
[ x ] No
```

RIA-6040 fix LR confirmation bug

---

Jenkinsfile_CNP
security.sh

https://tools.hmcts.net/jira/browse/RIA-6042
Fix nightly build (Added security.sh)
```
[ ] Yes
[ x ] No
```

RIA-6042 added security script

---

Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/RIA-6042
Added secrets for nightly builds
```
[ ] Yes
[ x ] No
```

RIA-6042 added secrets to Jenkinsfile_nightly

---

build.gradle
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/ccd/AssignCaseAccessConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/ccd/CcdCaseAssignmentConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/ccd/CcdCaseAssignmentProviderBaseTest.java
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/idam/IdamApiConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/idam/IdamConsumerApplication.java
src/contractTest/resources/application.properties
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/BadRequestsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/AddCaseNoteTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/MoveApplicationToDecidedTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/IaBailCaseApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/SpringBootIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/StaticPortWiremockFactory.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/TestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/WithUserDetailsStub.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/fixtures/BailCaseForTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/fixtures/Builder.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/fixtures/CallbackForTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/fixtures/CaseDetailsForTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/fixtures/PostSubmitCallbackResponseForTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/fixtures/PreSubmitCallbackResponseForTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/wiremock/CallbackTransformer.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/wiremock/DocumentsApiCallbackTransformer.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/component/testutils/wiremock/NotificationsApiCallbackTransformer.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/EditDocsCaseNoteServiceTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/HearingCentreTest.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamAuthoritiesConverter.java

https://tools.hmcts.net/jira/browse/RIA-6039
Added integration and contract tests
```
[ ] Yes
[ x ] No
```

Ria 6039 pact tests

---

src/functionalTest/resources/scenarios/RIA-5891-update-legal-rep-details-AboutToStart-email-appender.json
src/functionalTest/resources/scenarios/RIA-5891-update-legal-rep-details-AboutToSubmit-update-data.json
src/functionalTest/resources/scenarios/RIA-5891-update-legal-rep-details-confirmation.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/LegalRepresentativeUpdateDetailsConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/LegalRepresentativeUpdateDetailsConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeUpdateDetailsPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-5891
Added update legal rep details event
```
[ ] Yes
[ x ] No
```

RIA-5891 added update legal rep details event

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ShowPreviousApplicationConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ShowPreviousApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ShowPreviousApplicationSubmitHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ShowPreviousApplicationConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ShowApplicationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ShowPreviousApplicationSubmitHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-5622
Added show previous application data event
```
[ ] Yes
[ x ] No
```

Ria 5622 populate previous application details

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-6160
```
[ ] Yes
[ x ] No
```

RIA-6160 pipeline issue fix

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRole.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleLabel.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationSubmittedByAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentUserRoleAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/MakeNewApplicationService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelper.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleLabelTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentUserRoleAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/MakeNewApplicationServiceTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelperTest.java

https://tools.hmcts.net/jira/browse/RIA-6121
This is to allow any home office user with home office bails to process bails applications
```
[ ] Yes
[X ] No
```

Updates to fix home office bail permission

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java

- This is for the Previous Application view.

RIA-6296: Added Decision Document section in Document label

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DecisionTypeAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DecisionTypeAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java

Merge bails record decision changes to master
Merge bails record decision changes to master
Merge bails record decision changes to master
```
[ ] Yes
[X ] No
```

Merge bails record decision changes to master

---

build.gradle
config/owasp/suppressions.xml
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/ccd/CcdSupplementaryConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/ccd/CcdSupplementaryProviderBaseTest.java
src/contractTest/resources/application.properties
src/functionalTest/resources/scenarios/RIA-5851-start-application-confirmation.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/CcdSupplementaryUpdater.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/CcdSupplementaryUpdaterTest.java

https://tools.hmcts.net/jira/browse/RIA-6032
Adding hmctsServiceId to bail-case-api
```
[ ] Yes
[x] No
```

RIA-6032 - Adding hmctsServiceID to bail case api

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-6289
Adding in bail notifications for case linking events
```
[ ] Yes
[x] No
```

Ria 6289 bail case link notification

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/BailCaseDataFixingHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/config/BailCaseDataConfiguration.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/service/BailFieldCaseNameFixer.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/service/DataFixer.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/service/BailCaseNameFixerTest.java

RIA-6684 Added fixer to populate from full name

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
charts/ia-bail-case-api/Chart.yaml

To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[ X] No
```

To upgrade java chart version

---

charts/ia-bail-case-api/Chart.yaml

To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```

To revise chart version

---

config/owasp/suppressions.xml

To suppress CVEs to allow doc store release
To suppress CVEs to allow doc store release
```
[ ] Yes
[X ] No
```

To suppress CVEs to allow doc store release

---

charts/ia-bail-case-api/Chart.yaml

To update chart version 
To update chart version 
```
[ ] Yes
[X ] No
```

To update chart version 

---

charts/ia-bail-case-api/Chart.yaml

Reverts hmcts/ia-bail-case-api#332

Revert "To update chart version "

---

config/owasp/suppressions.xml

Reverts hmcts/ia-bail-case-api#331

Revert "To suppress CVEs to allow doc store release"

---

build.gradle
config/owasp/suppressions.xml

RIA-7719
Update libraries to solve outstanding vulnerabilities
```
[ ] Yes
[x] No
```

RIA-7719 Solve vulnerabilities

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java

https://tools.hmcts.net/jira/browse/SNI-4413
Added null check for case notes document when generating case notes label for Previous applciations
```
[ ] Yes
[x] No
```

SNI-4413 - fix NPE in Preview application case notes label generator

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-5679
Updating Suppressions
```
[ ] Yes
[x] No
```

RIA-5679 Adding suppressions

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-7386
Removed suppression of CVE-2023-41080, added dependency for it with specific version without vulnerability
```
[ ] Yes
[X] No
```

RIA-5679 Suppression-To-Dependency

---

.github/workflows/pr-title-validation.yml
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/refdata/ProfessionalOrganisationConsumerTest.java

https://tools.hmcts.net/jira/browse/DIAC-42
remove close connection
```
[ ] Yes
[x] No
```

DIAC-42 remove close connection

---

build.gradle
config/checkstyle/checkstyle.xml

Fix Checkstyle
```
[ ] Yes
[ x ] No
```

RIA-8888 fix checkstyle.xml

---

src/functionalTest/resources/scenarios/RIA-7990-create-flag-AboutToStart-party-role-applicant.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/StrategicCaseFlag.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/StrategicCaseFlagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7990
Updated party role Applicant
```
[ ] Yes
[ x  ] No
```

RIA-7990 Updated party role Applicant

---

src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-legal-rep-added.json
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-legal-rep-cleared.json
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-supporters-added.json
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-supporters-cleared.json
src/functionalTest/resources/scenarios/RIA-7996-start-application-generate-party-ids-applicant-legal-rep-supporters.json
src/functionalTest/resources/scenarios/RIA-7996-start-application-generate-party-ids-applicant-legal-rep.json
src/functionalTest/resources/scenarios/RIA-7996-start-application-generate-party-ids-applicant.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/PartyIdHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/PartyIdGenerator.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/PartyIdHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/PartyIdGeneratorTest.java

https://tools.hmcts.net/jira/browse/RIA-7996
- AboutToSubmit handler to generate party IDs to CCD field values for applicant, legal rep ind, legal rep org and financial condition supporters 1-4 during Start Application, Edit Bail Application and Edit Bail Application After Submit
- PartyID generator service class
- Unit and functional tests
```
[ ] Yes
[X] No
```

RIA-7996 Party ID generation

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java

https://tools.hmcts.net/jira/browse/RIA-8025
- Added new event 'Confirm detention location' to Event and EventTest
- Added event to admin event authorisations
```
[ ] Yes
[X] No
```

RIA-8025 Confirm detention location event added

---

Jenkinsfile_nightly
build.gradle

DIAC-123 dependency fixes 07/12/23

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/FcsInterpreterCategoryValidator.java

RIA-7953 Fix minor bugs FcsInterpreterCategoryValidator

---

src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/util/ResourceLoader.java
src/functionalTest/resources/scenarios/RIA-7992-create-flag-AboutToStart-party-role-fcs.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/StrategicCaseFlag.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CreateFlagHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/StrategicCaseFlagTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7992
Added FCS party level case flags
```
[ ] Yes
[ x ] No
```

RIA-7992 add case flag for fcs

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-8000
Added CVE-2023-6481 suppression
```
[ ] Yes
[ x ] No
```

RIA-8000 added CVE-2023-6481 suppression

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-7953
Fixed hasFCS data removal bug
```
[ ] Yes
[ x ] No
```

RIA-7953 Fixed hasFCS data removal bug

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/CaseFlagValue.java

https://tools.hmcts.net/jira/browse/RIA-8261
Fixed case flag details bug
```
[ ] Yes
[ x ] No
```

RIA-8261 Fixed case flag details bug

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RIA-7969
Give system user permission to "sendBailDirection" event
```
[ ] Yes
[ ] No
```

RIA-7969 send direction list case

---

Jenkinsfile_nightly
build.gradle
config/owasp/suppressions.xml

DIAC-184 build fix 18-12-23

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8362
Applicant interpreter booking status should be cleared when no interpreter requirements for Applicant
Applicant interpreter booking status should be reset when language requirements are updated for Applicant
FCS Interpreter booking status should be cleared when FCS is removed
FCS Interpreter booking status should be cleared when no interpreter requirements for FCS
FCS Interpreter booking status should be reset when language requirements are updated for FCS
```
[ ] Yes
[X ] No
```

RIA-8362 Updates to clear interpreter booking status information 

---

config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-8348-listing-case-confirmation-initialListing.json
src/functionalTest/resources/scenarios/RIA-8348-listing-case-confirmation-relisting.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ListingCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ListingCaseConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8348
Added caseListing event
```
[ ] Yes
[ x ] No
```

RIA-8348 Added caseListing event

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/util/AuthorizationHeadersProvider.java
src/functionalTest/resources/scenarios/RIA-5948-upload-bail-summary-confirmation.json
src/functionalTest/resources/scenarios/RIA-8355-case-listing-AboutToSubmit.json
src/functionalTest/resources/scenarios/RIA-8355-upload-bail-summary-AboutToStart-already-uploaded.json
src/functionalTest/resources/scenarios/RIA-8355-upload-bail-summary-AboutToSubmit-after-case-listing.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/eventvalidation/UploadBailSummaryEventValidChecker.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/eventvalidation/UploadBailSummaryEventValidCheckerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/util/LoggerUtil.java

https://tools.hmcts.net/jira/browse/RIA-8355
Added pre upload bail summary state
```
[ ] Yes
[ x ] No
```

RIA-8355 Added pre upload bail summary state

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8349
https://tools.hmcts.net/jira/browse/RIA-8352
- Adding event 'caseListing' to SendNotificationHandler to enable notifications to be sent
```
[ ] Yes
[X] No
```

RIA-8349 RIA-8352 Bail case listing notifications

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/MakeNewApplicationService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/config/BailCaseDataConfiguration.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/service/BailFieldCaseNameFixer.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/service/BailCaseNameFixerTest.java

https://tools.hmcts.net/jira/browse/RIA-8408
Added hearing case fields to make new application list
```
[ ] Yes
[ x ] No
```

RIA-8408 Added hearing case fields to make new application list

---

Dockerfile
Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/DIAC-108
```
[ ] Yes
[ ] No
```

DIAC-108 turning on fortify

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8448
Fixed case listing flag for bail summary upload
```
[ ] Yes
[ x ] No
```

RIA-8448 Fixed case listing flag for bail summary upload

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ListingEvent.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ListingCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DueDateService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/CountryHolidayDates.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/GovUkHolidayDatesClient.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/HolidayDate.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/HolidayLoader.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/HolidayService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/UkHolidayDates.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ListingEventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DueDateServiceTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/CountryHolidayDatesTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/HolidayDateTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/HolidayLoaderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/HolidayServiceTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/holidaydates/UkHolidayDatesTest.java

https://tools.hmcts.net/jira/browse/RIA-8353
Added case listing direction
```
[ ] Yes
[ x ] No
```

RIA-8353 Added case listing direction

---

src/functionalTest/resources/scenarios/RIA-8195-new-event-IMA-status.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ImaStatusConfirmation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ImaStatusConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-8195
new IMA status event
```
[ ] Yes
[x ] No
```

RIA-8195 new ima status event

---

src/functionalTest/resources/scenarios/RIA-8197-record-the-decision-AboutToSubmit-decision-type-appender-refused-under-ima-dgr.json
src/functionalTest/resources/scenarios/RIA-8197-record-the-decision-AboutToSubmit-decision-type-appender-refused-under-ima-dl.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/DecisionType.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DecisionTypeAppender.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/IsApplicantBeenRefusedFlagHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DecisionTypeAppenderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/IsApplicantBeenRefusedFlagHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8197
Added "refusal under IMA" option to Judge/Admin decision page, JUnit tests and FT
```
[ ] Yes
[ ] No
```

 RIA-8197 update_decision_option 

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/MakeNewApplicationService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java

https://tools.hmcts.net/jira/browse/RIA-8238
Added UT definitions and populate  VALID_ABOUT_TO_SUBMIT_MAKE_NEW_APPLICATION_FIELDS values in MakeNewApplicationService.class
```
[ ] Yes
[ ] No
```

RIA-8238 make_app_ut

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java

https://tools.hmcts.net/jira/browse/RIA-8499
- Content updated to match confluence for HO Bail summary direction
```
[ ] Yes
[X] No
```

RIA-8499 Content change for HO Bail summmary direction

---

src/functionalTest/resources/RIA-8410-generate-hearing-notice-on-case-listing-event.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ListingCaseConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ListingCaseConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/GenerateDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8410
```
[ ] Yes
[x] No
```

RIA-8410 Generate and store hearing notice on 'Case listing' event

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8410
```
[ ] Yes
[x] No
```

RIA-8410 Fix issue with casting to incompatible type

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DueDateService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/DueDateServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8494
Fix due date calculation
```
[ ] Yes
[ ] No
```

RIA-8494 fix due date calculation

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/FcsInterpreterCategoryValidator.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/FcsInterpreterCategoryValidatorTest.java

https://tools.hmcts.net/jira/browse/RIA-8497
Fixed FCS language validation bug
```
[ ] Yes
[ x ] No
```

RIA-8497 Fixed FCS language validation bug

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8198
Decision Refused under IMA - Notification to UT

RIA-8198 decision refused under ima

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/PartyIdHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/PartyIdHandlerTest.java

RIA-8517 Enable PartyIdHandler for MakeNewApplication event

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ImaStatusHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ImaStatusHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8195
https://tools.hmcts.net/jira/browse/RIA-8196
Changed the condition of showing IMA field to different users.(Admin create IMA status should be shown only for admins and judges).
```
[ ] Yes
[ ] No
```

RIA-8195 ima_showing_condition_fix

---

config/owasp/suppressions.xml

Update suppressions date
```
[ ] Yes
[ ] No
```

RIA-1111 fix_suppressions 

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
config/owasp/suppressions.xml
docker-pactbroker-compose.yml

https://tools.hmcts.net/jira/browse/DIAC-228
```
[ ] Yes
[ ] No
```

DIAC-228 dependency and fortify fixes

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ListingHearingCentre.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ShowPreviousApplicationHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ListingHearingCentreTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ShowApplicationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java

- Added enum for ListingHearingCentres.
```
[ ] Yes
[x] No
```

RIA-8421 Show hearing details on the Previous Applications

---

src/functionalTest/resources/scenarios/RIA-5955-edit-documents-MidEvent-error.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/editdocs/EditDocsMidEventHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/editdocs/EditDocsMidEventHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-212

DIAC-212 updating edit documents error message in line with case api

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java

RIA-8421 Fix Sonar failure

---

build.gradle
src/functionalTest/resources/scenarios/RIA-8000-Update-interpreter-details-confirmation.json
src/functionalTest/resources/scenarios/RIA-8001-Update-interpreter-booking-status-confirmation.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/UpdateInterpreterBookingStatusConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/UpdateInterpreterDetailsConfirmation.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/UpdateInterpreterBookingStatusConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/UpdateInterpreterDetailsConfirmationTest.java

https://tools.hmcts.net/jira/browse/RIA-8627
```
[ ] Yes
[x] No
```

RIA-8627 Update 'Success' screens for interpreter events

---

build.gradle
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ImaFeatureToggleHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MakeNewApplicationSubmitHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ImaFeatureToggleHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MakeNewApplicationSubmitHandlerTest.java

RIA-8232 set isImaEnabled at the submit of MAKE_NEW_APPLICATION event

---

src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java

https://tools.hmcts.net/jira/browse/DIAC-281
```
[ ] Yes
[ ] No
```

DIAC-281 fixing CcdScenarioRunnerTest

---

src/functionalTest/resources/scenarios/RIA-8195-new-event-IMA-status.json

https://tools.hmcts.net/jira/browse/RIA-8745
Fix failing test
```
[ ] Yes
[x ] No
```

RIA-8745 - Fix failing functional test

---

src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java

https://tools.hmcts.net/jira/browse/RIA-8745
Remove functional test exclusion
```
[ ] Yes
[x ] No
```

RIA-8745 - Remove functional test exclusion

---

build.gradle

https://tools.hmcts.net/jira/browse/DIAC-355
```
[ ] Yes
[ ] No
```

DIAC-355 dependency fix

---

Jenkinsfile_CNP
build.gradle
config/owasp/suppressions.xml
src/functionalTest/resources/scenarios/RIA-5851-start-application-AboutToStart-HO-user-role-appender.json
src/functionalTest/resources/scenarios/RIA-5851-start-application-AboutToStart-LR-ref-data.json
src/functionalTest/resources/scenarios/RIA-5914-edit-application-add-previous-case.json
src/functionalTest/resources/scenarios/RIA-5914-edit-application-change-hearing-centre.json
src/functionalTest/resources/scenarios/RIA-5914-edit-application-has-legal-rep.json
src/functionalTest/resources/scenarios/RIA-5914-edit-application-name.json
src/functionalTest/resources/scenarios/RIA-5914-edit-application-remove-nationality.json
src/functionalTest/resources/scenarios/RIA-5914-edit-application-submitted-by-appender.json
src/functionalTest/resources/scenarios/RIA-7945-edit-application-remove-legal-rep-details.json
src/functionalTest/resources/scenarios/RIA-7945-make-new-application-AboutToSubmit-HO-user-role-appender-legal-rep-before.json
src/functionalTest/resources/scenarios/RIA-7992-create-flag-AboutToStart-party-role-fcs-existing-flags.json
src/functionalTest/resources/scenarios/RIA-7992-create-flag-AboutToStart-party-role-fcs.json
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-legal-rep-added.json
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-legal-rep-cleared.json
src/functionalTest/resources/scenarios/RIA-7996-edit-application-generate-party-ids-supporters-cleared.json
src/functionalTest/resources/scenarios/RIA-8000-Update-interpreter-details-confirmation.json
src/functionalTest/resources/scenarios/RIA-8001-Update-interpreter-booking-status-confirmation.json
src/functionalTest/resources/scenarios/RIA-8355-case-listing-AboutToSubmit.json

[RIA-8774](https://tools.hmcts.net/jira/browse/RIA-8774)
- Functional tests run in AAT
```
[ ] Yes
[x] No
```

RIA-8774 Functional tests

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
charts/ia-bail-case-api/Chart.yaml
charts/ia-bail-case-api/values.preview.template.yaml
charts/ia-bail-case-api/values.yaml
pacts/ia_caseApi-referenceData_court_venues.json
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/refdata/LocationRefDataConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/bailcaseapi/consumer/refdata/RefDataConsumerApplication.java
src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java
src/functionalTest/resources/scenarios/RIA-8792-make-new-application-AboutToSubmit-ref-data-hearing-centre-appender.json
src/functionalTest/resources/scenarios/RIA-8792-start-application-AboutToSubmit-ref-datahearing-centre-appender.json
src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/HearingCentreTest.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingCentre.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/LocationRefDataService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/model/refdata/CourtLocationCategory.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/model/refdata/CourtVenue.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/refdata/LocationRefDataApi.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingCentreTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/HearingCentreFinderTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/LocationRefDataServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8792
```
[ ] Yes
[x] No
```

RIA-8792 Store epims id of Hearing centre when bail application is created

---

src/functionalTest/resources/scenarios/RIA-8793-edit-application-AboutToSubmit-ref-datahearing-centre-appender.json
src/functionalTest/resources/scenarios/RIA-8793-edit-application-post-submit-ref-datahearing-centre-appender.json

https://tools.hmcts.net/jira/browse/RIA-8793
* This PR contains only functional tests for the ticket [RIA-8793](https://tools.hmcts.net/jira/browse/RIA-8793).
* The implementation was taken care of by [RIA-8792](https://tools.hmcts.net/jira/browse/RIA-8792).
```
[ ] Yes
[x] No
```

RIA-8793 Store epims id of Hearing centre when bail application is edited

---

src/functionalTest/resources/scenarios/RIA-8802-case-listing-AboutToSubmit-initialListing-with-enabled-ref-data.json
src/functionalTest/resources/scenarios/RIA-8802-case-listing-AboutToSubmit-relisting-with-enabled-ref-data.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandler.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/LocationRefDataService.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/model/refdata/CourtVenue.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseListingHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/LocationRefDataServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8802
- save the details of ref data listing location in case field for document and notification API
- update the unit test
```
[ ] Yes
[X] No
```

RIA-8802 bails notice of hearing displays the correct location information

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java

https://tools.hmcts.net/jira/browse/DIAC-398
```
[ ] Yes
[ ] No
```

DIAC-398 no financial condition supporter on edit/make new fix

---

src/functionalTest/resources/scenarios/RIA-8801-make-new-application-AboutToSubmit-selected-hearing-centre-ref-data.json
src/functionalTest/resources/scenarios/RIA-8801-start-application-AboutToSubmit-selected-hearing-centre-ref-data.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DeriveHearingCentreHandler.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DeriveHearingCentreHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-8801
- create new case field for using the filter of tribunal centre
- store the ref data value into SELECTED_HEARING_CENTRE_REF_DATA case field when trigger START_APPLICATION, EDIT_BAIL_APPLICATION, MAKE_NEW_APPLICATION and EDIT_BAIL_APPLICATION_AFTER_SUBMIT event
- create/update unit test and functional test
```
[ ] Yes
[X] No
```

RIA-8801 Case list filters for tribunal centre use reference data

---

charts/ia-bail-case-api/Chart.yaml

DIAC-401 - update java charts

---

src/main/resources/application.yaml

RIA-8913 Updates to enable HO events for HO POU users
RIA-8913 Updates to enable HO events for HO POU users
```
[ ] Yes
[ ] No
```

RIA-8913 Updates to enable HO events for HO POU users

---

src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRole.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/security/idam/IdamUserDetailsHelper.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/UserRoleTest.java

RIA-8913 - To fix HO pou user permission issue
RIA-8913 - To fix HO pou user permission issue
```
[ ] Yes
[ ] No
```

RIA-8913 - To fix HO pou user permission issue

---

src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java

RIA-9110 Updates to fix FT scenario names
RIA-9110 Updates to fix FT scenario names
```
[ ] Yes
[ ] No
```

RIA-9110 Updates to fix FT scenario names

---

src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/HearingCentreTest.java
src/main/resources/application-hearingcentre-mapping.yaml

https://tools.hmcts.net/jira/browse/RIA-9190
RIA-9190 To perform below updates to prison lookup
Add - HM Prison Five Wells
Rename - HM Prison Glen Parva to HM Prison Fosse Way 
```
[ ] Yes
[ ] No
```

RIA-9190 to perform updates to prison lookup

---

src/integrationTest/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/HearingCentreTest.java
src/main/resources/application-hearingcentre-mapping.yaml

RIA-9190 updates to add fosse way to prison list
RIA-9190 updates to add fosse way to prison list
```
[ ] Yes
[ ] No
```

RIA-9190 updates to add fosse way to prison list

---

build.gradle
charts/ia-bail-case-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/DIAC-540
remove properties-volume-spring-boot-starter
```
[ ] Yes
[x] No
```

DIAC-540 - remove properties-volume-spring-boot-starter

---

src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java

RIA-0000 Update to disable CcdScenarioRunnerTest.java
RIA-0000 Update to disable CcdScenarioRunnerTest.java
```
[ ] Yes
[ ] No
```

RIA-0000 Update to disable CcdScenarioRunnerTest.java

---

src/functionalTest/java/uk/gov/hmcts/reform/bailcaseapi/CcdScenarioRunnerTest.java

Reverts hmcts/ia-bail-case-api#531

Revert "RIA-0000 Update to disable CcdScenarioRunnerTest.java"

---

build.gradle

https://tools.hmcts.net/jira/browse/DIAC-581
```
[ ] Yes
[ ] No
```

DIAC-581 drop mutation threshold

---

build.gradle
src/functionalTest/resources/scenarios/DIAC-528-upload-hearing-recording-details.json
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingRecordingDocument.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/UploadHearingRecordingConfirmation.java
src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadHearingRecordingDocumentsMidEvent.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/UploadHearingRecordingConfirmationTest.java
src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadHearingRecordingDocumentsMidEventTest.java

https://tools.hmcts.net/jira/browse/DIAC-528
Adding event for bails cases for uploadHearingRecordingDocument
```
[ ] Yes
[x] No
```

DIAC-528 Adding-Hearing-Recording-Document-Uploader

---

charts/ia-bail-case-api/values.preview.template.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DIAC-649
Add role event access mappings for robot user role
```
[ ] Yes
[x] No
```

DIAC-649 Add role event access for robot user role
