hmcts/ia-bail-case-api

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
https://tools.hmcts.net/jira/browse/RIA-5487
As an admin user,
I want to select the Record the decision event,
So that I can record the decision.
Acceptance Criteria :
Record the decision event can be triggered after upload bail summary only by admin.
Record the decision event should be shown in the list as attached.
```
[ ] Yes
[x] No
```
> RIA-5487-Record-the-Decision-Event/State

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/RecordDecisionAppender.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/RecordDecisionAppenderTest.java
https://tools.hmcts.net/jira/browse/RIA-5490
Added a field into RecordDecisionAppender to pre-populate on bail transfer screen. Plus in the unit test.
```
[ ] Yes
[X] No
```
> RIA-5490 Bail transfer field pre-population 

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/SignedDecisionNoticeUploadedConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/SignedDecisionNoticeUploadedConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandlerTest.java
[RIA-5519](https://tools.hmcts.net/jira/browse/RIA-5519)
Addition of all the fundamental changes to set up a new event (Upload Signed Decision Notice), i.e.:
- addition to State, Event, DocumentTag, BailCaseFieldDefinitions
- creation of a pre-event handler and a post-event handler
- amendment of existing tests and addition of new ones for the new classes
```
[ ] Yes
[x] No
```
> RIA-5519 Add UploadSignedDecisionNotice event

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/IntermediateState.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/IntermediateStateTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdaterTest.java
- Updated current state to new intermediate state for Event.UPLOAD_SIGNED_DECISION_NOTICE.
- Changed the currentCaseStateVisibleTo* variables type to String from State.
> RIA-5532: Added intermediate state for uploadSignedDecisionNotice

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
[RIA-5214](https://tools.hmcts.net/jira/browse/RIA-5214)
Allow END_APPLICATION to be among the events for which notifications will be handled.
```
[ ] Yes
[x] No
```
> RIA-5214 Add END_APPLICATION to events to handle for notifications

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/DocumentsUploadedConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppender.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentUserRoleAppender.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/DocumentsUploadedConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationUserRoleAppenderTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentUserRoleAppenderTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadBailSummaryDocumentHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadDocumentsHandlerTest.java
[RIA-5545](https://tools.hmcts.net/jira/browse/RIA-5545)
- Refactored 'UploadBailSummaryDocumentHandler' so that it appends the Bail Summary to a collection of documents called _Home Office documents_ (similar to the upload of a signedDecisionNotice being handled as an appendage of Tribunal documents)
- The refactor is necessary because of how the uploaded documents will look like in the documents tab. There will be (1) Applicant Documents, (2) Home Office Documents, (3) Tribunal Documents. And Bail Summary is a Home office document.
- Acceptance criteria require the following:
- HO can upload a document (it's a **HO document**)
- Legal Rep can upload a document (it's an **Applicant document**)
- Admin/Judge can upload a document but have to select if it's a **HO document**, an …
> Ria 5545 handle documents upload

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/IntermediateState.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/EndApplicationConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/MoveApplicationToDecidedConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdater.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/EndApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MoveApplicationToDecidedHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/IntermediateStateTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/EndApplicationConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/MoveApplicationToDecidedConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CurrentCaseStateUpdaterTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/EndApplicationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/MoveApplicationToDecidedHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/UploadSignedDecisionNoticeHandlerTest.java
* Ria 5345 uploaded bail summary notification email (#79)
* RIA-5610: Added delegator to send requests to Documents API & Notific… (#67)
* RIA-5610: Added delegator to send requests to Documents API & Notifications API
- Added handler for document generation on Application Submission.
- Added missing CaseFieldDefinitions.
- Added relevant tests.
* RIA-5610: Suppressing vulnerabilities
Co-authored-by: Neha Aggarwal <neha.aggarwal@version1.com>
* RIA-5455 Adding case state updater to allow state based filtering wit… (#64)
* RIA-5455 Adding case state updater to allow state based filtering within CCD
* RIA-5455 Adding CVEs to suppression prior to fixing in separate ticket
Co-authored-by: NehaAggarwal <nehaaggarwal.1987@gmail.com>
* RIA-5584: Added Notification Handler and Notification API …
> Merge dev to master (#117)

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/Direction.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/SendDirectionConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DirectionTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/SendDirectionConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-5556
As an admin/judge 
I want to send the direction to parties,
So that they are aware of what to do next.
Acceptance Criteria
Send direction event can be triggered at application submitted, listing, bail summary, hearing state
Send direction should be shown in the event list as attached (send_direction_event.png)
Send direction event can be triggered in 2 ways.
Select Send direction event from the dropdown
Click on Send a new direction link from the directions tab.
Then the following screens should appear in the order.
1) Direction details
1.1 Free text box to explain the direction you are issuing
1.2 Dropdown to select who are you giving the direction to ?
Dropdown should have the values
Select a value
Legal representative
Home Office
Applicant …
> Ria 5556 UI screens

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/Direction.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DirectionTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendDirectionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
[RIA-5597](https://tools.hmcts.net/jira/browse/RIA-5597)
- Added SEND_BAIL_DIRECTION to the list of events to send notifications for
```
[x] Yes (if merged before notifications)
[x] No (if merged after notifications)
```
> RIA-5597 Add SEND_BAIL_DIRECTION to events to handle for notifications

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/SendNotificationHandlerTest.java
[RIA-5559](https://tools.hmcts.net/jira/browse/RIA-5559)
- Added "editBailDocuments" to events to be handled for notifications
```
[ ] Yes
[x] No
```
> RIA-5559 Add "editBailDocuments" to SendNotificationHandler

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseInferenceByBailNumberHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseInferenceByBailNumberHandlerTest.java
[RIA-5763](https://tools.hmcts.net/jira/browse/RIA-5763)
- Added explicit setting of flags even for sad path, in order to prevent screens showing up when flags (used as show conditions) are set and then not overwritten when going back and forth through the journey
```
[ ] Yes
[x] No
```
> RIA-5763 Explicitly set flags also for sad path

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/callback/Callback.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseInferenceByBailNumberHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ErrorForStartApplicationAppender.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/PreSubmitCallbackDispatcher.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CaseInferenceByBailNumberHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ErrorForStartApplicationAppenderTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java
[RIA-5763](https://tools.hmcts.net/jira/browse/RIA-5763)
- A first midEvent handler was already present (CaseInferenceByBailNumberHandler) which can be activated when:
- event is START_APPLICATION
- stage is MID_EVENT
- pageId is `hasPreviousBailApplication` (the first page in Start Application)
- ErrorForStartApplicationAppender is a second midEvent handler which can be activated when:
- event is START_APPLICATION
- stage is MID_EVENT
- pageId is `redirectToPreviousApplicationOrNoc` (the first page in Start Application)
- PreSubmitCallbackController has been expanded to include an optional `@RequestParam` which is the `pageId`. The `pageId` is added to a new field in `Callback` if it's not null, so that the handlers can use it to understand which midEvent handler is intended to work. …
> RIA-5763 Add midEvent handler + expand midEvent endpoint

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/PopulatePreviousApplicationsHandler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/MakeNewApplicationService.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/PopulatePreviousApplicationsHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/MakeNewApplicationServiceTest.java
- Modified MakeNewApplicationService to clear previousApplicationData
before appending the application to PriorApplication fielf.
- Added method to convert given string to BailCase.
```
[ ] Yes
[ ] No
```
> RIA-5621: Added handler to populate the list of previous applications

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/Organisation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/OrganisationPolicy.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/field/ChangeOrganisationRequest.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsAppender.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/CcdCaseAssignment.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/CcdDataIntegrationException.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/OrganisationPolicyTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/OrganisationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepresentativeDetailsAppenderTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/CcdCaseAssignmentTest.java
[RIA-5764](https://tools.hmcts.net/jira/browse/RIA-5764)
- The event gets triggered from the NoC shared componed, so there's no presubmit handler.
- There's only a postsubmit handler (ChangeRepresentationConfirmation)
- The LegalRepresentativeDetailsAppender has been expanded to include the LegalAuthorityPolicy when appending the LR's details (mainly for the organizationId)
```
[ ] Yes
[x] No
```
> RIA-5764 Add all necessary classes + tests for NoC

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatter.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/LegalRepOrganisationFormatterTest.java
[RIA-5765](https://tools.hmcts.net/jira/browse/RIA-5765)
- When calling BailApplicationSavedConfirmation the assignment of the case should be tampered with only if it's a LR
- Add confirmation body to ChangeRepresentationConfirmation success page
```
[ ] Yes
[x] No
```
> Ria 5765 Don't mess with access if not LR

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseTest.java
[RIA-5905](https://tools.hmcts.net/jira/browse/RIA-5905)
- 18 fields needed their type changed (e.g. "Text" -> "PhoneUK"). This throws a mapping error in Elastic Search and a quick workaround is to change the name of the field in CCD. This PR reflects those changes.
**Fields that changed:**
applicantMobileNumber
financialCondAmount
supporterTelephoneNumber
supporterMobileNumber
supporterEmailAddress
financialAmountSupporterUndertakes
supporter2TelephoneNumber
supporter2MobileNumber
supporter2EmailAddress
financialAmountSupporter2Undertakes
supporter3TelephoneNumber
supporter3MobileNumber
supporter3EmailAddress
financialAmountSupporter3Undertakes
supporter4TelephoneNumber
supporter4MobileNumber
supporter4EmailAddress
financialAmountSupporter4Undertakes
**Does this PR introduce a breaking …
> RIA-5905 Change field names (values)

- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
RIA-7385
Some formatting is applied directly by the IDE.
The removed checkstyle rules enforced a behaviour different than the IDE's default. They get in the way often and provided little to no utility.
```
[ ] Yes
[x] No
```
> RIA-7385 Removed pendantic checkstyle rules

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/ia-bail-case-api/Chart.yaml
- charts/ia-bail-case-api/values.preview.template.yaml
- charts/ia-bail-case-api/values.yaml
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/ConfigValidatorAppListener.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/ConfigValidatorAppListenerTest.java
https://tools.hmcts.net/jira/browse/RIA-7383
Adding ia.config.validator.secret to application.yaml + ConfigValidatorAppListener to check to see if secrets are being applied by azure.
```
[ ] Yes
[x] No
```
> RIA-7378 - preventing application startup if secrets can't be found

- src/functionalTest/resources/scenarios/RIA-7949-start-application-MidEvent-fcs-contact-preferences-fail-no-email.json
- src/functionalTest/resources/scenarios/RIA-7949-start-application-MidEvent-fcs-contact-preferences-fail-no-phone.json
- src/functionalTest/resources/scenarios/RIA-7949-start-application-MidEvent-fcs-contact-preferences-success.json
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ContactPreference.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/FinancialConditionSupporterContactPreferenceMidEventHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ContactPreferenceTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/FinancialConditionSupporterContactPreferenceMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-7949
- MidEvent handler to add error validation when email or phone contact preferences are not checked for FCS 1-4 for Start Application, Edit Application (pre and post submit), Make an Application
- New Enum class for Contact Pref values
- New unit tests and functional tests for success and failure scenarios
```
[ ] Yes
[X] No
```
> RIA-7949 FCS contact pref mid event handler - error validation

- build.gradle
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8311
- Clearing isDetentionLocationCorrect after edit post submit when this value already exists to fix bug with wrong progress bar field showing
```
[ ] Yes
[X] No
```
> RIA-8311 Clearing isDetentionLocationCorrect after edit post submit

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8311
- Checking that IS_DETENTION_LOCATION_CORRECT = NO and then clearing the field. This is so that when IS_DETENTION_LOCATION_CORRECT = YES, it isn't cleared when the application is edited again
```
[ ] Yes
[X] No
```
> RIA-8311 Adding equals(NO) check before clearing detention location field

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CreateFlagHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/CreateFlagHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8310
- Instead of reading from interpreter category fields for FCS, read HAS_FINANCIAL_COND_SUPPORTER fields which allows case flags to be created for each FCS on the case regardless of if there is an interpreter requirement or not
- This allows event 'Create flag' to show FCS as an option
- 'Manage flags' can then be used to modify any existing case flags
```
[ ] Yes
[X] No
```
> RIA-8310 Allowing case flags to be created for FCS regardless of interpreter reqs

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandler.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/ApplicationDataRemoveHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8445
- Defaulting fcsInterpreterYesNo field to No when you edit an application pre or post submit to remove all FCS from the case. This screen won't show in the event so is still saving as Yes in the caseData and showing as yes in the Bail Application summary document. This resolves that issue
```
[ ] Yes
[X] No
```
> RIA-8445 Defaulting fcsInterpreterYesNo to No when FCS are removed when editing

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingCentre.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-8488
- Updated yarlswood to Yarlswood in HearingCentre class to match what is used in Hearings-api for appeals and bails hearings
```
[ ] Yes
[X] No
```
> RIA-8488 updated yarlswood to yarlsWood Hearing Centre

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8420
- Adding hearing documents field to ia-bail-case-api then displaying them on the screen for View Previous Applications
- Document link also available to open in browser
```
[ ] Yes
[X] No
```
> RIA-8420 Display hearing documents on previous applications screen

- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationService.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/ShowPreviousApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8507
- FCS passport number is an optional CCD field, so checking it's present before appending to label in previous applications
- This allows you to view previous applications as mid event will not throw exception when it's missing
- Updated unit test 
```
[ ] Yes
[X] No
```
> RIA-8507 Fix bug for previous applications with optional FCS passport number

- charts/ia-bail-case-api/Chart.yaml
Bump charts version
Some of the template versions/names were straightened out in the 5.2.1 release. We're hoping this will help fix https://tools.hmcts.net/jira/browse/DIAC-401
> DIAC-401 Update Chart Version

- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/ia-bail-case-api/Chart.yaml
- charts/ia-bail-case-api/values.preview.template.yaml
- charts/ia-bail-case-api/values.yaml
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSavedConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmation.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/presubmit/DecisionTypeAppender.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/domain/service/Scheduler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/AsylumCaseServiceResponseException.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/TimedEventMessageConverterCustomizer.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/TimedEventServiceApi.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/TimedEventServiceScheduler.java
- src/main/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/model/TimedEvent.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/domain/handlers/postsubmit/BailApplicationSubmittedConfirmationTest.java
- src/test/java/uk/gov/hmcts/reform/bailcaseapi/infrastructure/clients/TimedEventServiceSchedulerTest.java
https://tools.hmcts.net/jira/browse/DIAC-577
integrating Timed Event Service into bail-case-api
```
[ ] Yes
[ ] No
```
> DIAC-577 integrating Timed Event Service into bail-case-api #537
